### ISSUE TITLE
Failed to activate the atom-deconsole package

### ISSUE THREAD

**Issue by amarinelli** [hughsk/atom-deconsole#2]
1. Error appears after installing atom-deconsole or when restarting atom

**Atom Version**: 1.0.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [atom-deconsole](git://github.com/hughsk/atom-deconsole) package, v0.0.1
### Stack Trace

Failed to activate the atom-deconsole package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.exports.activate (C:\Users\amarinelli\.atom\packages\atom-deconsole\index.js:5:21)
    at Package.module.exports.Package.activateNow (C:\Users\amarinelli\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:240:19)
    at C:\Users\amarinelli\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:221:30
    at Package.module.exports.Package.measure (C:\Users\amarinelli\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:165:15)
    at Package.module.exports.Package.activate (C:\Users\amarinelli\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\amarinelli\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:452:21)
    at C:\Users\amarinelli\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:436:29
    at Config.module.exports.Config.transact (C:\Users\amarinelli\AppData\Local\atom\app-1.0.0\resources\app.asar\src\config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\amarinelli\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:431:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\amarinelli\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:412:46)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-deconsole, v0.0.1
minimap, v4.10.1

# Dev
No dev packages
```

**Comment by rammoozz** [comment]
I just experienced this!

**Comment by mattandrews** [comment]
Me too. Atom 1.6.0 on OS X 10.10.5.

Stacktrace:

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.exports.activate (/Users/andrem43/.atom/packages/atom-deconsole/index.js:5:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
